---
- name: create nginx dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    recurse: yes
  with_items:
    - "{{ sites_available }}"
    - "{{ sites_enabled }}"
    - "{{ conf_d }}"
  tags:
    -nginx

- name: transfer nginx.conf configuration
  template:
    src: "{{ item }}"
    dest: "{{ nginx_path }}/nginx.conf"
  with_fileglob:
    - ../templates/config/nginx.conf
  tags:
    -nginx

- name: transfer mime.types configuration
  template:
    src: "{{ item }}"
    dest: "{{ nginx_path }}/mime.types"
  with_fileglob:
    - ../templates/config/mime.types
  tags:
    -nginx
